# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where', to='worker.Partment', verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='container',
            name='partment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Partment', verbose_name='所属部门'),
        ),
    ]
