# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20161123_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='location',
            field=models.CharField(max_length=20, verbose_name='箱子所在地'),
        ),
    ]
