# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import worker.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='位置')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='worker.Partment', verbose_name='上级部门')),
            ],
            options={
                'verbose_name_plural': '部门',
                'verbose_name': '部门',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('personId', models.CharField(blank=True, max_length=18, validators=[worker.validators.IdCardValidator()], verbose_name='身份证号')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='头像')),
                ('workerId', models.CharField(blank=True, max_length=20, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='姓名')),
                ('status', models.CharField(choices=[('working', '正在工作'), ('relaxing', '休息')], default='working', max_length=20, verbose_name='工作状态')),
                ('profile', models.CharField(choices=[('guarder', '押解员'), ('watcher', '仓库管理员'), ('driver', '司机'), ('banker', '银行验收员')], max_length=10, verbose_name='身份')),
                ('partment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Partment', verbose_name='所属部门')),
            ],
            options={
                'verbose_name_plural': '工作人员',
                'verbose_name': '工作人员',
            },
        ),
    ]
