# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile',
            field=models.CharField(choices=[('guarder', '押解员'), ('watcher', '仓库管理员'), ('driver', '司机'), ('banker', '银行验收员')], max_length=10, verbose_name='身份'),
        ),
    ]
