# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.BooleanField(default=True, verbose_name='是为模板，否为任务')),
                ('time_start', models.DateTimeField(verbose_name='开始时间')),
                ('time_end', models.DateTimeField(verbose_name='结束时间')),
                ('current_task', models.SmallIntegerField(default=0, verbose_name='当前任务')),
            ],
            options={
                'verbose_name_plural': '任务',
                'verbose_name': '任务',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_time', models.DateTimeField(null=True, verbose_name='当天时间')),
                ('modified', models.DateTimeField(verbose_name='状态改变时间')),
                ('status', models.CharField(choices=[('receive', '已入库'), ('load', '已装货，将前往下一个目的地'), ('done', '已完成，将前往下一个目的地'), ('failed', '未进行'), ('finish', '已结束')], max_length=10, verbose_name='状态')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('load_container', models.ManyToManyField(blank=True, to='container.Container', verbose_name='装货箱')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Mission', verbose_name='任务')),
            ],
            options={
                'verbose_name_plural': '任务节点',
                'verbose_name': '任务节点',
            },
        ),
    ]
