# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('time_start', models.DateTimeField(verbose_name='开始时间')),
                ('time_end', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name_plural': '任务',
                'verbose_name': '任务',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(verbose_name='状态改变时间')),
                ('status', models.CharField(choices=[('doing', '正在执行'), ('done', '已完成'), ('failed', '未完成')], max_length=10, verbose_name='状态')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('container', models.ManyToManyField(to='container.Container', verbose_name='货箱')),
                ('misson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Misson', verbose_name='任务')),
            ],
            options={
                'verbose_name_plural': '任务节点',
                'verbose_name': '任务节点',
            },
        ),
    ]
