# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('worker', '0001_initial'),
        ('container', '0002_auto_20161123_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Partment', verbose_name='起点'),
        ),
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending', to='worker.Partment', verbose_name='目标点'),
        ),
        migrations.AddField(
            model_name='misson',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.Car', verbose_name='执行车'),
        ),
        migrations.AddField(
            model_name='misson',
            name='worker',
            field=models.ManyToManyField(to='worker.Worker', verbose_name='押运工作人员'),
        ),
    ]
