# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-28 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20161123_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Misson',
            new_name='Mission',
        ),
    ]
