# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20161123_1348'),
        ('task', '0003_auto_20161128_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='added',
            new_name='time_added',
        ),
        migrations.RemoveField(
            model_name='task',
            name='container',
        ),
        migrations.AddField(
            model_name='task',
            name='load_container',
            field=models.ManyToManyField(null=True, to='container.Container', verbose_name='装货箱'),
        ),
        migrations.AddField(
            model_name='task',
            name='unload_container',
            field=models.ManyToManyField(null=True, related_name='unloading', to='container.Container', verbose_name='卸货箱'),
        ),
    ]
