# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20161202_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='load_container',
            field=models.ManyToManyField(blank=True, null=True, to='container.Container', verbose_name='装货箱'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unload_container',
            field=models.ManyToManyField(blank=True, null=True, related_name='unloading', to='container.Container', verbose_name='卸货箱'),
        ),
    ]
