# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20161202_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='task',
            name='origin',
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='当天时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='load_container',
            field=models.ManyToManyField(blank=True, to='container.Container', verbose_name='装货箱'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Partment', verbose_name='目标点'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unload_container',
            field=models.ManyToManyField(blank=True, related_name='unloading', to='container.Container', verbose_name='卸货箱'),
        ),
    ]
