# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-03 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20161202_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='template',
            field=models.BooleanField(default=True, verbose_name='是为模板，否为任务'),
            preserve_default=False,
        ),
    ]
