# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-04 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20161203_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='misson',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='mission_time',
        ),
    ]
