# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20161204_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='current_task',
            field=models.SmallIntegerField(default=0, verbose_name='当前任务'),
        ),
    ]
