# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20161206_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='target',
        ),
    ]
