# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_mission_current_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='target',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('receive', '已入库'), ('load', '已装货，将前往下一个目的地'), ('done', '已完成，将前往下一个目的地'), ('failed', '未进行'), ('finish', '已结束')], max_length=10, verbose_name='状态'),
        ),
    ]
